name: po_project
services:
  auth-service:
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/po_db
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: po_db
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass
    ports:
      - "5424:5432"

  restaurant-service:
    build:
      context: ../RestaurantService
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/po_db
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8082:8082"
    depends_on:
      - db

  order-service:  
    build:
      context: ../OrderService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/po_db
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - auth-service
      - restaurant-service
      - order-service
