services:
  auth-service:
    build:
      context: ../AuthService .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/po_db
      SPRING_DATASOURCE_USERNAME: user2
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: po_db
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: pass
    ports:
      - "5423:5432"
